-- ─── Live Trading Signals Table ─────────────────────────
--
--  Stores signals generated by the Live Strategy Engine.
--  Supports both paper and live trading modes.
--
--  Phase 2: This table will be used to persist signal history
--  and drive the signals/results dashboard.
--

CREATE TABLE IF NOT EXISTS public.signals (
  id              TEXT PRIMARY KEY,
  strategy_id     UUID NOT NULL REFERENCES public.strategies(id) ON DELETE CASCADE,
  portfolio_id    UUID REFERENCES public.portfolios(id) ON DELETE SET NULL,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  symbol          TEXT NOT NULL,
  type            TEXT NOT NULL CHECK (type IN ('buy', 'sell')),
  price           NUMERIC(12, 4) NOT NULL,
  quantity        INTEGER NOT NULL DEFAULT 0,
  confidence      NUMERIC(4, 3) NOT NULL DEFAULT 0.0,
  reason          TEXT,
  mode            TEXT NOT NULL DEFAULT 'paper' CHECK (mode IN ('paper', 'live')),
  acknowledged    BOOLEAN NOT NULL DEFAULT false,
  executed        BOOLEAN NOT NULL DEFAULT false,
  trade_id        UUID REFERENCES public.trades(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_signals_strategy   ON public.signals(strategy_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_user       ON public.signals(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_symbol     ON public.signals(symbol, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_executed   ON public.signals(executed, created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view their own signals
CREATE POLICY "Users can view own signals"
  ON public.signals
  FOR SELECT
  USING (auth.uid() = user_id);

-- RLS Policy: Users can insert their own signals
CREATE POLICY "Users can insert own signals"
  ON public.signals
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS Policy: Users can update their own signals (e.g., acknowledge)
CREATE POLICY "Users can update own signals"
  ON public.signals
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);